// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAifAN6bcFvvYf3Si4K48mTCs39SLOb29A',
    appId: '1:998018651905:web:6a89b3d7da4d256b476d00',
    messagingSenderId: '998018651905',
    projectId: 'loginauthaquatrace',
    authDomain: 'loginauthaquatrace.firebaseapp.com',
    storageBucket: 'loginauthaquatrace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHuoSrJAkne86NZYh3verO7D34xeCrK84',
    appId: '1:998018651905:android:1bbae17739618f35476d00',
    messagingSenderId: '998018651905',
    projectId: 'loginauthaquatrace',
    storageBucket: 'loginauthaquatrace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBanZUO2M_nepTFdL-ipGeAhXZuhV7USP8',
    appId: '1:998018651905:ios:9625fcd0aaa5b366476d00',
    messagingSenderId: '998018651905',
    projectId: 'loginauthaquatrace',
    storageBucket: 'loginauthaquatrace.appspot.com',
    iosBundleId: 'com.example.aquaTrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBanZUO2M_nepTFdL-ipGeAhXZuhV7USP8',
    appId: '1:998018651905:ios:042277098690f559476d00',
    messagingSenderId: '998018651905',
    projectId: 'loginauthaquatrace',
    storageBucket: 'loginauthaquatrace.appspot.com',
    iosBundleId: 'com.example.aquaTrace.RunnerTests',
  );
}
