List<String> tips_widgets = [
  "Fix Leaks Promptly: Even a small drip can waste significant amounts of water over time.",
  "Use Water-Saving Appliances: Look for appliances and fixtures that are water-efficient.",
  "Don’t Let the Tap Run: Don’t leave the tap running while brushing your teeth or washing dishes.",
  "Water Plants Wisely: Water plants during the cooler parts of the day to reduce evaporation.",
  "Use a Rain Barrel: Collect rainwater and use it to water your plants.",
  "Take Shorter Showers: Reducing your shower time can save a lot of water.",
  "Install a Dual-Flush Toilet: These toilets have two flush options - a half flush for liquid waste and a full flush for solid waste.",
  "Reuse Greywater: If it’s safe and legal in your area, reuse greywater for things like watering plants or flushing toilets.",
  "Use a Broom, Not a Hose: Use a broom to clean driveways, sidewalks, and patios rather than hosing them down.",
  "Wash Full Loads: Only run your washing machine and dishwasher when you have a full load.",
  "Install Water-Saving Showerheads: These can significantly reduce the amount of water used during showers.",
  "Use a Pool Cover: This can reduce water loss due to evaporation.",
  "Plant Drought-Resistant Plants: These require less water and are often more resistant to pests.",
  "Use a Car Wash: Most car washes recycle water, making them a more water-efficient option.",
  "Insulate Your Pipes: This can reduce the amount of time it takes for hot water to heat up, saving water and energy.",
  "Use a Dishwasher: Dishwashers typically use less water than washing dishes by hand.",
  "Water Your Lawn Wisely: Water your lawn during the early morning or late evening to reduce evaporation.",
  "Use a Water Meter: This can help you track your water usage and identify leaks.",
  "Install a Water-Efficient Toilet: These use significantly less water per flush than traditional toilets.",
  "Use a Watering Can: This can be more water-efficient than using a hose for small gardening tasks.",
  "Remember, every drop counts! 💧",
];
